package entity;
// Generated Apr 11, 2016 12:24:46 AM by Hibernate Tools 4.3.1



/**
 * AddCandidate1 generated by hbm2java
 */
public class AddCandidate1  implements java.io.Serializable {


     private Integer candidateId;
     private String markName;
     private String candidateName;
     private String candidateImage;

    public AddCandidate1() {
    }

    public AddCandidate1(String markName, String candidateName, String candidateImage) {
       this.markName = markName;
       this.candidateName = candidateName;
       this.candidateImage = candidateImage;
    }
   
    public Integer getCandidateId() {
        return this.candidateId;
    }
    
    public void setCandidateId(Integer candidateId) {
        this.candidateId = candidateId;
    }
    public String getMarkName() {
        return this.markName;
    }
    
    public void setMarkName(String markName) {
        this.markName = markName;
    }
    public String getCandidateName() {
        return this.candidateName;
    }
    
    public void setCandidateName(String candidateName) {
        this.candidateName = candidateName;
    }
    public String getCandidateImage() {
        return this.candidateImage;
    }
    
    public void setCandidateImage(String candidateImage) {
        this.candidateImage = candidateImage;
    }




}


