package entity;
// Generated Apr 11, 2016 12:24:46 AM by Hibernate Tools 4.3.1



/**
 * AddCandidate generated by hbm2java
 */
public class AddCandidate  implements java.io.Serializable {


     private Integer candidateId;
     private Mark mark;
     private String candidateName;
     private String candidateImage;

    public AddCandidate() {
    }

    public AddCandidate(Mark mark, String candidateName, String candidateImage) {
       this.mark = mark;
       this.candidateName = candidateName;
       this.candidateImage = candidateImage;
    }
   
    public Integer getCandidateId() {
        return this.candidateId;
    }
    
    public void setCandidateId(Integer candidateId) {
        this.candidateId = candidateId;
    }
    public Mark getMark() {
        return this.mark;
    }
    
    public void setMark(Mark mark) {
        this.mark = mark;
    }
    public String getCandidateName() {
        return this.candidateName;
    }
    
    public void setCandidateName(String candidateName) {
        this.candidateName = candidateName;
    }
    public String getCandidateImage() {
        return this.candidateImage;
    }
    
    public void setCandidateImage(String candidateImage) {
        this.candidateImage = candidateImage;
    }




}


