package entity;
// Generated Apr 11, 2016 12:24:46 AM by Hibernate Tools 4.3.1



/**
 * AddVoter generated by hbm2java
 */
public class AddVoter  implements java.io.Serializable {


     private int voterId;
     private String voterName;

    public AddVoter() {
    }

    public AddVoter(int voterId, String voterName) {
       this.voterId = voterId;
       this.voterName = voterName;
    }
   
    public int getVoterId() {
        return this.voterId;
    }
    
    public void setVoterId(int voterId) {
        this.voterId = voterId;
    }
    public String getVoterName() {
        return this.voterName;
    }
    
    public void setVoterName(String voterName) {
        this.voterName = voterName;
    }




}


