package entity;
// Generated Apr 11, 2016 12:24:46 AM by Hibernate Tools 4.3.1



/**
 * Voting generated by hbm2java
 */
public class Voting  implements java.io.Serializable {


     private int voterId;
     private Mark mark;

    public Voting() {
    }

    public Voting(int voterId, Mark mark) {
       this.voterId = voterId;
       this.mark = mark;
    }
   
    public int getVoterId() {
        return this.voterId;
    }
    
    public void setVoterId(int voterId) {
        this.voterId = voterId;
    }
    public Mark getMark() {
        return this.mark;
    }
    
    public void setMark(Mark mark) {
        this.mark = mark;
    }




}


